"""
Runs the document-category classifier over every PDF in test_samples/
(plus test_samples/from_acord/, generated from ACORD's real held-out test
clauses, and test_samples/from_internet/, if you've added your own real
PDFs there) and reports accuracy plus a confusion matrix for each source
separately.

Folder layout expected:
    test_samples/
        Business_and_Commercial_Contracts/  sample_01.pdf ...
        Real_Estate_and_Property_Documents/ sample_01.pdf ...
        Estate_Planning_Documents/          sample_01.pdf ...
        Court_and_Litigation_Pleadings/     sample_01.pdf ...

        from_acord/                          <-- generated by build_acord_samples.py
            Business_and_Commercial_Contracts/  acord_test_01.pdf ...
            (no other categories: ACORD only covers commercial contracts)

        from_internet/                       <-- optional, you add these yourself
            Business_and_Commercial_Contracts/  ...
            Real_Estate_and_Property_Documents/ ...
            Estate_Planning_Documents/           ...
            Court_and_Litigation_Pleadings/      ...

Usage:
    python tests/evaluate_categories.py
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import fitz  # PyMuPDF

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from legalrisk.document_classifier import detect_document_category  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent / "test_samples"

FOLDER_TO_CATEGORY = {
    "Business_and_Commercial_Contracts": "Business and Commercial Contracts",
    "Real_Estate_and_Property_Documents": "Real Estate and Property Documents",
    "Estate_Planning_Documents": "Estate Planning Documents",
    "Court_and_Litigation_Pleadings": "Court and Litigation Pleadings",
}


def extract_text(path: Path) -> str:
    doc = fitz.open(path)
    try:
        text = "\n".join(page.get_text("text") for page in doc)
    finally:
        doc.close()
    return text


def run_over(base_dir: Path, label: str):
    if not base_dir.exists():
        return None

    rows = []
    confusion = defaultdict(lambda: defaultdict(int))

    for folder_name, true_category in FOLDER_TO_CATEGORY.items():
        folder = base_dir / folder_name
        if not folder.exists():
            continue
        for pdf_path in sorted(folder.glob("*.pdf")):
            text = extract_text(pdf_path)
            result = detect_document_category(text)
            correct = result.matches(true_category) and result.predicted == true_category
            rows.append((pdf_path.name, true_category, result.predicted, result.confidence, correct))
            confusion[true_category][result.predicted] += 1

    if not rows:
        return None

    print(f"\n=== {label} ===")
    print(f"{'file':<28}{'true':<22}{'predicted':<22}{'conf':<8}{'ok'}")
    for name, true_cat, pred, conf, ok in rows:
        print(f"{name:<28}{true_cat:<22}{pred:<22}{conf:<8}{'✓' if ok else '✗'}")

    correct_n = sum(1 for *_, ok in rows if ok)
    accuracy = correct_n / len(rows)
    print(f"\nStrict accuracy (predicted == true category exactly): {correct_n}/{len(rows)} = {accuracy:.1%}")

    # "Gate accuracy": in the actual app, a document is only ever rejected
    # if the classifier is CONFIDENTLY wrong about its category — "Uncertain"
    # always passes through (see CategoryResult.matches()). This is a more
    # representative measure of real-world behaviour: it asks "would this
    # real document have been wrongly blocked from its correct section?"
    gate_ok = sum(1 for name, true_cat, pred, conf, ok in rows
                  if pred in (true_cat, "Uncertain"))
    gate_accuracy = gate_ok / len(rows)
    print(f"Gate accuracy (not wrongly rejected from its true section): "
          f"{gate_ok}/{len(rows)} = {gate_accuracy:.1%}")

    print("\nConfusion matrix (rows = true category, cols = predicted):")
    categories = sorted(FOLDER_TO_CATEGORY.values()) + ["Uncertain"]
    header = "".ljust(24) + "".join(c[:10].ljust(12) for c in categories)
    print(header)
    for true_cat in sorted(FOLDER_TO_CATEGORY.values()):
        row = true_cat.ljust(24)
        for pred_cat in categories:
            row += str(confusion[true_cat].get(pred_cat, 0)).ljust(12)
        print(row)

    return accuracy


def main():
    run_over(ROOT, "1. In-house synthetic dataset (test_samples/)")
    run_over(
        ROOT / "from_acord",
        "2. Real ACORD test-split clauses, from data/acord/ (test_samples/from_acord/) "
        "— Business & Commercial Contracts only; ACORD has no Real Estate, Estate "
        "Planning, or Litigation data",
    )
    run_over(ROOT / "from_internet", "3. Real-world PDFs found online (test_samples/from_internet/)")


if __name__ == "__main__":
    main()
